### ISSUE TITLE
Commit on Windows not committing the entire message

### ISSUE THREAD

**Issue by davidhouweling** [leoforfree/cz-customizable#133]
Machine: Windows 10 Pro Version 2004
Setup: using [option 2 - standalone](https://github.com/leoforfree/cz-customizable#option-2---cz-customizable-in-standalone-mode-new)

Issue: after filling out all the prompts, when you check the commit message it only includes the title. It doesn't include the body or footer content in the entirety is there as part of https://github.com/leoforfree/cz-customizable/blob/65d364656a0bd61b8146a3e42cdd720158ebcc96/standalone.js#L13

I verified it by doing a `console.log` and can see the content appropriately being multi-lined. I'm thinking its an issue with the `git commit` statement where for Windows we should use multiple `-m` commands instead of trying to do pass it all into 1. Alternatively try using a tool like [`cross-spawn`](https://www.npmjs.com/package/cross-spawn) or [`execa`](https://www.npmjs.com/package/execa) instead of the inbuilt [`child_process`](https://nodejs.org/api/child_process.html).

**Comment by davidhouweling** [comment]
I decided to try using `commitizen` with [option 1 - as a commitizen plugin](https://github.com/leoforfree/cz-customizable#option-1---cz-customizable-as-commitizen-plugin) and its working that way.

**Comment by ronyf** [comment]
Any updates?
