### ISSUE TITLE
Add a 'allowEmptyScope' option.

### ISSUE THREAD

**Issue by reivon** [leoforfree/cz-customizable#151]
Hello,

Actually, when we set option 'allowCustomScopes' to false, we can't choose the empty option.

I want to authorize to select an empty scope or some existing scope only, but not custom one.

Add an option 'allowEmptyScopes' can resolve this issue;

Thanks lots

**Comment by jvanbruegge** [comment]
I think this is solved by #152

**Comment by jvanbruegge** [comment]
Also, I wrote a cz-customizable alternative that does this by default: https://github.com/jvanbruegge/commithelper
