### ISSUE TITLE
Can the prefix be removed from the last message?

### ISSUE THREAD

**Issue by imagine10255** [leoforfree/cz-customizable#154]
Hello,

Can the prefix be removed from the last message?

Thanks lots

--
first is 「修正 首頁輪播自動播放 activeIndex, autoPlay setTimeout 重複註冊問題」

then modify commit

![CleanShot 2021-04-06 at 16 59 51](https://user-images.githubusercontent.com/5771353/113686165-8ce87600-96f9-11eb-9a0e-ce7c1765e88a.png)

**Comment by Fuphoenixes** [comment]
you can use version 6.1.0

**Comment by cmzylks** [comment]
如何设置不提示最后一条消息

**Comment by imagine10255** [comment]
Currently changed to use https://github.com/Zhengqbbb/cz-git as a replacement
