### ISSUE TITLE
if my package.json type: 'module'

### ISSUE THREAD

**Issue by davidchen27** [leoforfree/cz-customizable#199]
when my package.json type is 'module'
i run 'git cz', it will report:
![image](https://user-images.githubusercontent.com/44220311/179394178-ae3ebdb7-e74d-425c-844b-7460dd053335.png)

if i change the config file's name: .cz-config.cjs, and modify package.json
![image](https://user-images.githubusercontent.com/44220311/179394250-d0b4e275-af66-4b40-a086-d07b100c784c.png)

it will report:
![image](https://user-images.githubusercontent.com/44220311/179394280-f0313daa-5bfa-4930-bc70-e406b2dcc86f.png)

does it not support  .cjs config file？

**Comment by SelinaYu** [comment]
same  question

**Comment by hezhongfeng** [comment]
same question

**Comment by general-guan** [comment]
same question

**Comment by ND-LJQ** [comment]
same question

**Comment by gyhyfj** [comment]
same question, wish it could recognize `.cz-config.cjs`, like eslint and stylelint

**Comment by patrickcate** [comment]
Running into the same issue.

**Comment by patrickcate** [comment]
Just a followup. I have found a workaround using the `package.json` config option.

1. Rename `.cz-config.js` to `.cz-config.cjs`
2. In `package.json` add the following:

```
"config": {
    "cz-customizable": {
        "config": ".cz-config.cjs"
    }
}
```

**Comment by daiwanxing** [comment]
> "cz-customizable": {
>         "config": ".cz-config.cjs"
>     }

It's work for me. Thanks

**Comment by daiwanxing** [comment]
> Just a followup. I have found a workaround using the `package.json` config option.
> 
> 1. Rename `.cz-config.js` to `.cz-config.cjs`
> 2. In `package.json` add the following:
> 
> ```
> "config": {
>     "cz-customizable": {
>         "config": ".cz-config.cjs"
>     }
> }
> ```

It's work for me. Thanks

**Comment by LittleWorker** [comment]
> 

it's works for me , thanks a lot.

**Comment by LittleWorker** [comment]
> Just a followup. I have found a workaround using the `package.json` config option.
> 
> 1. Rename `.cz-config.js` to `.cz-config.cjs`
> 2. In `package.json` add the following:
> 
> ```
> "config": {
>     "cz-customizable": {
>         "config": ".cz-config.cjs"
>     }
> }
> ```
it's works for me , thanks a lot.

**Comment by linpengteng** [comment]
To solve this same problem, I created cz-message-helper npm package, hope it helps.

**Comment by qiuqimin** [comment]
> Just a followup. I have found a workaround using the `package.json` config option.
> 
> 1. Rename `.cz-config.js` to `.cz-config.cjs`
> 2. In `package.json` add the following:
> 
> ```
> "config": {
>     "cz-customizable": {
>         "config": ".cz-config.cjs"
>     }
> }
> ```

`hint: Waiting for your editor to close the file... "C:\Users\qiu.qimin\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait: C:\Users\qiu.qimin\AppData\Local\Programs\Microsoft VS Code\bin\code: No such file or directory
error: There was a problem with the editor '"C:\Users\qiu.qimin\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait'.
Please supply the message using either -m or -F option.`

why i got this
