### ISSUE TITLE
No scope question error(Denote the SCOPE of this change)

### ISSUE THREAD

**Issue by manudeli** [leoforfree/cz-customizable#201]
I met no scope question(Denote the SCOPE of this change) commitizen in v6.9.1
but there's no error about scope question (Denote the SCOPE of this change) in v6.9.0

# Expected
<img width="345" alt="image" src="https://user-images.githubusercontent.com/61593290/182126987-dc025472-7ab6-433e-8041-a786e8bfb685.png">

# Error cases of recent Version(v6.9.1) - skip custom scope field

## [CASE 1] If .cz-config.js's scopes is defined
<img width="516" alt="image" src="https://user-images.githubusercontent.com/61593290/182177166-0d51d117-42ac-49e9-a69b-2560a1932b64.png">

## [CASE 2] if .cz-config.js's scopes is not defined
<img width="560" alt="image" src="https://user-images.githubusercontent.com/61593290/182176658-ac0591af-2e23-4059-b621-d4a4a9d8a7fc.png">

I think it need to be reset

**Comment by manudeli** [comment]
Check this picture! there is customScope, not every custom.

<img width="2162" alt="image" src="https://user-images.githubusercontent.com/61593290/182135647-0970ab28-d260-4a32-8b49-faa3173b7bbf.png">

but recent version of cz-customizable have every scope name as 'custom' when I use customScope, no changeable

**Comment by XPoet** [comment]
I also encountered this problem with cz-customizable `v6.9.1`

**Comment by manudeli** [comment]
> I also encountered this problem with `cz-customizable v6.9.1`

If you want to avoid this problem, you can use v6.9.0 first.

**Comment by chensidi** [comment]
After setting allowCustomScopes to true and adding scopes: ['custom'] to the scopes option, I can't enter the value of the scope manually.

How should I solve it

**Comment by XPoet** [comment]
@chensidi 
You can use **[cz-custom](https://github.com/XPoet/cz-customizable/tree/dev)**, which is exactly the same as cz-customizable.
```
// install cz-custom
npm i cz-custom -D

// modify package.json
"config": {
    "commitizen": {
      "path": "cz-custom"
    },
    "cz-custom": {
      "config": ".cz-config.cjs"
    }
  }
```

**Comment by chensidi** [comment]
> @chensidi You can use **[cz-custom](https://github.com/XPoet/cz-customizable/tree/dev)**, which is exactly the same as cz-customizable.
> 
> ```
> // install cz-custom
> npm i cz-custom -D
> 
> // modify package.json
> "config": {
>     "commitizen": {
>       "path": "cz-custom"
>     },
>     "cz-custom": {
>       "config": ".cz-config.cjs"
>     }
>   }
> ```

**Comment by chensidi** [comment]
> @chensidi You can use **[cz-custom](https://github.com/XPoet/cz-customizable/tree/dev)**, which is exactly the same as cz-customizable.
> 
> ```
> // install cz-custom
> npm i cz-custom -D
> 
> // modify package.json
> "config": {
>     "commitizen": {
>       "path": "cz-custom"
>     },
>     "cz-custom": {
>       "config": ".cz-config.cjs"
>     }
>   }
> ```

@XPoet 
感谢大佬，试了一下确实可以输入自定义scope
但是想问下，这个cz-custom和cz-customizable有什么关系，目前cz-customizable是^6.9.1，但cz-custom只有0.0.2
这是新仓库吗？望赐教😊😊😊

**Comment by XPoet** [comment]
@chensidi 
因为 cz-customizable 目前存在自定义 scope 无效的问题，我提了修复该 bug 的 PR，但作者没合并。于是我自己在  cz-customizable 的基础上并发布新的 NPM 包 **cz-custom**，其用法和文档跟 cz-customizable 保持一致。
当然我会一直维护，跟  cz-customizable 保持功能上的同步，同时也会推出一些更好的功能。你也可以一直使用 cz-custom，没有本质上的区别。

**Comment by chensidi** [comment]
@XPoet 好的，希望原作者能看到及时合并，感谢大佬支持
@leonardoanalista Currently custom scopes, the problem that cannot be manually entered, hope to merge PR in time，Thank you very much

**Comment by baixjian** [comment]
> @chensidi 因为 cz-customizable 目前存在自定义 scope 无效的问题，我提了修复该 bug 的 PR，但作者没合并。于是我自己在 cz-customizable 的基础上并发布新的 NPM 包 **cz-custom**，其用法和文档跟 cz-customizable 保持一致。 当然我会一直维护，跟 cz-customizable 保持功能上的同步，同时也会推出一些更好的功能。你也可以一直使用 cz-custom，没有本质上的区别。

您好，请问下使用cz-custom，如果不配置scope项的话，customScope也没有填写，怎么才能移除掉feat(custom): xxx中的 custom。
![snapshot](https://raw.githubusercontent.com/baixjian/imgs/main/z.jpg)

```js
module.exports = {
  types: [....],
  messages: {
    type: '请选择提交类型(必填)',
    scope: '选择一个scope (可选):',
    customScope: '请输入文件修改范围(可选)',
    subject: '请简要描述提交(必填)',
    body: '请输入详细描述(可选)',
    breaking: '列出任何BREAKING CHANGES(破坏性修改)(可选)',
    footer: '请输入要关闭的issue(可选)',
    confirmCommit: '确定提交此说明吗？'
  },
  skipQuestions: ['body', 'footer'],
  allowCustomScopes: true,
  allowBreakingChanges: ['feat', 'fix'], // 当提交类型为feat、fix时才有破坏性修改选项
  subjectLimit: 72
}

**Comment by XPoet** [comment]
@baixjian 
增加 allowEmptyScopes 配置，可以不填写 Scope
```js
module.exports = {
  ...
 
  allowEmptyScopes: true, // 允许空 Scope （增加这个配置项）
  emptyScopesName:  'empty               （不填 Scope）', // 可自由填写你想要显示的文字

  ....
  
}
```

<img width="945" alt="image" src="https://user-images.githubusercontent.com/24516169/185014733-27869bad-1ff5-47d4-b611-312ed9795fd1.png">

看文档，有些每个配置项的用法：
https://github.com/XPoet/cz-customizable/tree/dev

**Comment by leonardoanalista** [comment]
Thank you all. I'll merge it as soon as the PR is green.

**Comment by wakaka378** [comment]
Has this problem been fixed?
I encountered this problem

"cz-customizable": "^7.0.0",


<img width="530" alt="image" src="https://user-images.githubusercontent.com/46524158/211019965-e5d376ba-228a-4bd6-8ac8-9c5fa940bba1.png">
