### ISSUE TITLE
[BUG?] Cannot input custom scope when choose custom, help!!

### ISSUE THREAD

**Issue by seepine** [leoforfree/cz-customizable#210]
## Recurrence steps
run command
```sh
git cz
```
choose anyone type, and then choose custom scope.
it should let me input scope, but it let me input subject directly.

## Additional
The generated commit msg like `fix(custom): fix some bug`.
And the same configuration works normally on some colleagues' computers.

## Environment

|   name   | version|
|----|----|
|  cz-cli    |  4.2.5    |
|    cz-customizable| 7.0.0 |
|   git   |    2.17.1.windows.2 |
| node |    v16.15.1        |
|   SystemOs |  windows10 enterprise ltsc |

**Comment by linpengteng** [comment]
If you need it urgently, You can fix that bug(#214) to yarn pacth-package or use `cz-message-helper` npm package.

**Comment by wangrongding** [comment]
Is it difficult to solve the problem that my custom scope cannot be entered? Why hasn't it been fixed for such a long time? 🥲
